### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by vasani-arpit** [dynamsoft-dbr/node-javascript-barcode#3]
### Getting following error

```
0|index  | ReferenceError: self is not defined
0|index  |     at Function.<anonymous> (/root/barcode-reader/node_modules/dynamsoft-node-barcode/dist/dbr.js:11:37428)
0|index  |     at Generator.next (<anonymous>)
0|index  |     at /root/barcode-reader/node_modules/dynamsoft-node-barcode/dist/dbr.js:11:34867
0|index  |     at new Promise (<anonymous>)
0|index  |     at s (/root/barcode-reader/node_modules/dynamsoft-node-barcode/dist/dbr.js:11:34615)
0|index  |     at Function.loadWasm (/root/barcode-reader/node_modules/dynamsoft-node-barcode/dist/dbr.js:11:37279)
0|index  |     at Function.<anonymous> (/root/barcode-reader/node_modules/dynamsoft-node-barcode/dist/dbr.js:11:41682)
0|index  |     at Generator.next (<anonymous>)
0|index  |     at /root/barcode-reader/node_modules/dynamsoft-node-barcode/dist/dbr.js:11:34867
0|index  |     at new Promise (<anonymous>)
```
## Here is the code which I am running 

```javascript

const express = require('express');
const dotenv = require('dotenv');
dotenv.config();

const app = express();

app.post('/test', async (req, res) => {

  let Dynamsoft = require('dynamsoft-node-barcode');
  // Please visit https://www.dynamsoft.com/CustomerPortal/Portal/TrialLicense.aspx to get a trial license
  Dynamsoft.BarcodeReader.productKeys = process.env.LICENCSE_KEY;

  let reader = await Dynamsoft.BarcodeReader.createInstance();
  let response = [];
  for (let result of await reader.decode('https://demo.dynamsoft.com/dbr/img/AllSupportedBarcodeTypes.png')) {
    response.push(result.barcodeText);
  }
  res.send({ result: response })
  reader.destroy();
})

app.listen(PORT, () => console.log(`BAR CODE READER SERVER AT PORT: ${PORT}`));
```

Also I have noticed that purchased key is very small compared to trial one. 

Trial License --> xxxxxxQAAALU5iIEu4UvLOwuP1jRYrIEkJemxC7qJk0DjzJ2sU1rBSyCh0GQ5ooGrvgzQ/8tqennPSf7T3uFu5JgiTt35RFpBzaubL7Hxxxxx
Purchased License --> xxxac2xx

Please reply at earliest. Our production is down due to this.

**Comment by Keillion** [comment]
Hi @vasani-arpit , Sorry to reply you so late.

Dynamsoft currently puts the main focus of javascript-barcode on browser. The `xxxac2xx` is called as runtimeKeys, which is not supported by node edition.

I call our technical support to contact your email to help you solve this problem.

If allowed, I would be happy to help you complete runtimeKeys/handshakecode support for node on version 8.

**Comment by vasani-arpit** [comment]
@Keillion 

Thanks for the response. I have reached out to support and after purchasing the two types of license this thing didn't resolved.  
At the end, Support people has provided me a key which is working for me. 

Why this simple license has to be this complicated? can't you guys provide both types of key in your customer portal? seems like you are overcomplicating things for your user.
